=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/itm/Itm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:Itm="http://www.td-tech.com/ubp/platform/Itm/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/Itm/xml">
  <xsd:simpleType name="tasktype">
     <xsd:restriction base="xsd:string">
       <xsd:enumeration value="DB"/>
       <xsd:enumeration value="FILE"/>
     </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="cycletype">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Hour"/>
      <xsd:enumeration value="Day"/>
      <xsd:enumeration value="Week"/>
      <xsd:enumeration value="Month"/>	  
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="intervaldays">
    <xsd:restriction base="xsd:integer">
      <xsd:minInclusive value="0"/>
      <xsd:maxInclusive value="365"/>
    </xsd:restriction>
  </xsd:simpleType>  
  <xsd:complexType name="Table">
    <xsd:attribute name="Tablename" type="xsd:string" use="required"/>
    <xsd:attribute name="Col" type="xsd:string" use="required"/>
    <xsd:attribute name="Intervaldays" type="Itm:intervaldays" use="required"/>
    <xsd:attribute name="SysLogInfo" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="Tables">
    <xsd:sequence>
      <xsd:element name="Table" type="Itm:Table" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence> 
  </xsd:complexType>
  <xsd:complexType name="TaskInfo">
    <xsd:sequence>
      <xsd:element name="Tables" type="Itm:Tables" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="TaskName" type="xsd:string" use="required"/>
    <xsd:attribute name="StartTime" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="Cycle" type="Itm:cycletype" use="required"/>
    <xsd:attribute name="Type" type="Itm:tasktype" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="TaskInfos">
    <xsd:sequence>
      <xsd:element name="TaskInfo" type="Itm:TaskInfo" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="TaskInfos" type="Itm:TaskInfos"/>
</xsd:schema>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/itm/Itm_platform.xml
<?xml version="1.0" encoding="UTF-8"?>
<Itm:TaskInfos xmlns:Itm="http://www.td-tech.com/ubp/platform/Itm/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.td-tech.com/ubp/platform/Itm/xml Itm.xsd">
  <TaskInfo TaskName="PLT_TrunkLogs" StartTime="2014-12-25T23:40:00" Cycle="Day" Type="DB">
    <Tables>
      <Table Tablename="TBL_UbpSyncSsnAlarm" Col="raiseTime" Intervaldays="90" SysLogInfo="trunk alarm logs"/>
      <Table Tablename="TBL_UserLog" Col="OpTime" Intervaldays="90" SysLogInfo="trunk user logs"/>
      <Table Tablename="TBL_SysLog" Col="OpTime" Intervaldays="90" SysLogInfo="trunk system logs"/>
      <Table Tablename="TBL_FeatureLog" Col="OpTime" Intervaldays="90" SysLogInfo="trunk feature logs"/>
      <Table Tablename="TBL_SecurityLog" Col="OpTime" Intervaldays="90" SysLogInfo="trunk security logs"/>
    </Tables>
  </TaskInfo>
</Itm:TaskInfos>
