=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/svc_agent_4.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
file      : \code\src\platform\modules\sca\svc_agenty.xsd
install   : \install\conf\svc_agenty.xsd
author    : ZhongWei
created   : 2012/10/30 13:30
changed	  : 2015-4-17 2:38 to support 4.0 by huangchunlun 
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/sca/xml">
	<xsd:complexType name="Param_t">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="SvcParams_t">
		<xsd:sequence>
			<xsd:element name="Param" type="sca:Param_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  
	<xsd:complexType name="Module_t">
		<xsd:attribute name="lib" type="xsd:string" use="required"/>
		<xsd:attribute name="entry" type="xsd:string" default="CreateModule"/>
	</xsd:complexType>
	<xsd:complexType name="LoadModules_t">
		<xsd:sequence>
			<xsd:element name="Module" type="sca:Module_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="LoadPB_t">
		<xsd:sequence>
			<xsd:element name="PB" type="sca:Module_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Svc_t">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="DependSvcs_t">
		<xsd:sequence>
			<xsd:element name="Svc" type="sca:Svc_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  
  <xsd:complexType name="ServiceInfo_t">
    <xsd:sequence>
      <xsd:element name="SvcParams" type="sca:SvcParams_t" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="LoadModules" type="sca:LoadModules_t" maxOccurs="unbounded" minOccurs="0"/>
	  <xsd:element name="LoadPB" type="sca:LoadPB_t" maxOccurs="unbounded" minOccurs="0"/>
	  <xsd:element name="DependSvcs" type="sca:DependSvcs_t" maxOccurs="unbounded" minOccurs="0"/>	  
    </xsd:sequence>
    <xsd:attribute name="svc_type" type="xsd:string" use="required"/>
	<xsd:attribute name="code_type" type="xsd:string" use="required"/>
	<xsd:attribute name="valgrind_trigger" type="xsd:string" use="optional" default="off" />
	<xsd:attribute name="tcmalloc_trigger" type="xsd:string" use="optional" default="off" />
	<xsd:attribute name="user" type="xsd:string" use="required"/>
	<xsd:attribute name="team" type="xsd:string" use="required"/>
  </xsd:complexType>
  
	<xsd:complexType name="SvcAgent_t">
		<xsd:sequence>
			<xsd:element name="ServiceInfo" type="sca:ServiceInfo_t" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	
  <xsd:element name="svcagent" type="sca:SvcAgent_t"/>
  
</xsd:schema>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/mrs_plb_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="mrs_plb_agent" code_type="cplus" user="ubp" team="MRS" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_mrs_plb"/>
        <Param name="dbenable" value="True"/>
        <Param name="db_max_conn" value="5"/>
        <Param name="db_min_conn" value="3"/>
        <Param name="rtsp_port" value="8554"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/tis_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="tis_agent" code_type="java" user="ubp" team="UDC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="start_java" value="/opt/UBP/bin/tis_webstart.sh"/>
        <Param name="pid_java" value="/opt/UBP/bin/tis_query_tomcat.sh"/>
        <Param name="stop_java" value="/opt/UBP/bin/tis_webstop.sh"/>
        <Param name="init_wait_time" value="60"/>
      </SvcParams>
      <LoadModules>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
        <Svc name="web_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/mon_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="mon_agent" code_type="cplus" user="ubp" team="PLT" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_monitor"/>
        <Param name="detect_switch" value="1"/>
        <Param name="dbenable" value="True"/>
        <Param name="periodic_time" value="300"/>
        <Param name="disk_used_threshold_percent" value="80"/>
        <Param name="memory_used_threshold_percent" value="90"/>
        <Param name="cpu_used_threshold_percent" value="90"/>
        <Param name="systime_check_period" value="5"/>
        <Param name="diff_time" value="60"/>
        <Param name="delay_reboot" value="5"/>
        <Param name="cpu_detect_count" value="5"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
        <Module lib="ubp_mon_proxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="lm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/hpgw_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="hpgw_agent" code_type="java" user="ubp" team="BCC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="start_java" value="/opt/UBP/bin/hpgw_webstart.sh"/>
        <Param name="pid_java" value="/opt/UBP/bin/hpgw_status.sh"/>
        <Param name="stop_java" value="/opt/UBP/bin/hpgw_webstop.sh"/>
        <Param name="init_wait_time" value="120"/>
      </SvcParams>
      <LoadModules>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/bcc_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="bcc_agent" code_type="cplus" user="ubp" team="BCC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_bcc"/>
        <Param name="dbenable" value="true"/>
        <Param name="rtpport_start" value="28002"/>
        <Param name="rtpport_num" value="8999"/>
        <Param name="rtpport_start_alone" value="25000"/>
        <Param name="rtpport_num_alone" value="18002"/>
        <Param name="register_output" value="0"/>
        <Param name="invite_output" value="0"/>
        <Param name="cancel_output" value="1"/>
        <Param name="ack_output" value="1"/>
        <Param name="bye_output" value="1"/>
        <Param name="option_output" value="3"/>
        <Param name="info_output" value="1"/>
        <Param name="response_100_output" value="1"/>
        <Param name="response_180_output" value="1"/>
        <Param name="response_183_output" value="1"/>
        <Param name="response_200_output" value="1"/>
        <Param name="response_400_output" value="1"/>
        <Param name="response_401_output" value="2"/>
        <Param name="response_403_output" value="1"/>
        <Param name="response_404_output" value="1"/>
        <Param name="response_407_output" value="2"/>
        <Param name="response_420_output" value="1"/>
        <Param name="response_450_output" value="1"/>
        <Param name="response_480_output" value="1"/>
        <Param name="response_481_output" value="1"/>
        <Param name="response_486_output" value="1"/>
        <Param name="response_487_output" value="1"/>
        <Param name="response_488_output" value="1"/>
        <Param name="response_491_output" value="1"/>
        <Param name="response_493_output" value="1"/>
        <Param name="response_500_output" value="1"/>
        <Param name="response_501_output" value="1"/>
        <Param name="response_503_output" value="1"/>
        <Param name="response_603_output" value="1"/>
        <Param name="init_wait_time" value="120"/>
        <Param name="fir_req_list" value="HUAWEI TEx0,HUAWEI VP"/>
		<Param name="eSpace_Agent" value="Huawei eSpace"/>
        <Param name="video_transcode_license_on_one_bdc" value="4"/>
        <Param name="video_transcode_license_on_multi_bdc" value="76"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
        <Module lib="ubp_lic_man_proxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
        <Svc name="lic_man_agent" />
        <Svc name="hpgw_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/daem_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="daem_agent" code_type="cplus" user="ubp" team="PLT" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="max_retry_times" value="100"/>
        <Param name="check_state_interval" value="10"/>
        <Param name="heartbeat_interval" value="30"/>
        <Param name="default_service_init_waittime" value="45"/>
        <Param name="default_service_fini_waittime" value="30"/>
        <Param name="all_service_init_waittime" value="120"/>
        <Param name="all_service_fini_waittime" value="60"/>
        <Param name="master_host_ip" value=""/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
        <Module lib="ubp_cgroup" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/itf_mgr_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="itf_mgr_agent" code_type="cplus" user="ubp" team="SDK" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_itf_mgr"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="sdk_frm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/sdk_frm_common.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="sdk_frm_common" code_type="cplus" user="ubp" team="SDK" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="itf_manager_listen_port" value="8200"/>
        <Param name="itf_manager_enable_heartbeat" value="1"/>
        <Param name="cert_path" value="/opt/UBP/conf/cert/eAPP610.cer"/>
        <Param name="key_path" value="/opt/UBP/conf/cert/eAPP610_Ky.pem"/>
        <Param name="ubp_sdk_agent_01" value="22121"/>
        <Param name="ubp_sdk_agent_02" value="22122"/>
        <Param name="ubp_sdk_agent_03" value="22123"/>
        <Param name="ubp_sdk_agent_04" value="22124"/>
        <Param name="ubp_sdk_agent_05" value="22125"/>
        <Param name="ubp_sdk_agent_06" value="22126"/>
        <Param name="ubp_sdk_agent_07" value="22127"/>
        <Param name="ubp_sdk_agent_08" value="22128"/>
        <Param name="ubp_sdk_agent_09" value="22129"/>
        <Param name="ubp_sdk_agent_10" value="22130"/>
        <Param name="curwkey" value="3CD512317830B5677AAF7C7E3D3BC17D73F71D0F133702AAE7F68A5B13D37D954D75E089E505E5A8BA00054D0F48CE16B7FF70B895C92A673FD031C25C10796E"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>
