=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/svc_agent_4.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
file      : \code\src\platform\modules\sca\svc_agenty.xsd
install   : \install\conf\svc_agenty.xsd
author    : ZhongWei
created   : 2012/10/30 13:30
changed	  : 2015-4-17 2:38 to support 4.0 by huangchunlun 
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/sca/xml">
	<xsd:complexType name="Param_t">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="SvcParams_t">
		<xsd:sequence>
			<xsd:element name="Param" type="sca:Param_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  
	<xsd:complexType name="Module_t">
		<xsd:attribute name="lib" type="xsd:string" use="required"/>
		<xsd:attribute name="entry" type="xsd:string" default="CreateModule"/>
	</xsd:complexType>
	<xsd:complexType name="LoadModules_t">
		<xsd:sequence>
			<xsd:element name="Module" type="sca:Module_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="LoadPB_t">
		<xsd:sequence>
			<xsd:element name="PB" type="sca:Module_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Svc_t">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="DependSvcs_t">
		<xsd:sequence>
			<xsd:element name="Svc" type="sca:Svc_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  
  <xsd:complexType name="ServiceInfo_t">
    <xsd:sequence>
      <xsd:element name="SvcParams" type="sca:SvcParams_t" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="LoadModules" type="sca:LoadModules_t" maxOccurs="unbounded" minOccurs="0"/>
	  <xsd:element name="LoadPB" type="sca:LoadPB_t" maxOccurs="unbounded" minOccurs="0"/>
	  <xsd:element name="DependSvcs" type="sca:DependSvcs_t" maxOccurs="unbounded" minOccurs="0"/>	  
    </xsd:sequence>
    <xsd:attribute name="svc_type" type="xsd:string" use="required"/>
	<xsd:attribute name="code_type" type="xsd:string" use="required"/>
	<xsd:attribute name="valgrind_trigger" type="xsd:string" use="optional" default="off" />
	<xsd:attribute name="tcmalloc_trigger" type="xsd:string" use="optional" default="off" />
	<xsd:attribute name="user" type="xsd:string" use="required"/>
	<xsd:attribute name="team" type="xsd:string" use="required"/>
  </xsd:complexType>
  
	<xsd:complexType name="SvcAgent_t">
		<xsd:sequence>
			<xsd:element name="ServiceInfo" type="sca:ServiceInfo_t" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	
  <xsd:element name="svcagent" type="sca:SvcAgent_t"/>
  
</xsd:schema>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/mrs_vgw_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="mrs_vgw_agent" code_type="cplus" user="ubp" team="MRS" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_mrs_vgw"/>
        <Param name="dbenable" value="True"/>
        <Param name="db_max_conn" value="5"/>
        <Param name="db_min_conn" value="3"/>
        <Param name="hikvision_sdk_connect_time" value="2000"/>
        <Param name="hikvision_sdk_log_level" value="0"/>
        <Param name="hikvision_sdk_exception_ignore_level" value="0"/>
        <Param name="huawei_sdk_play_local_ip" value=""/>
        <Param name="huawei_sdk_log_enable" value="0"/>
        <Param name="yaan_getvideo_trigger_exception_max_error_num" value="3"/>
        <Param name="rtcp_timeout" value="180"/>
        <Param name="ptz_monitor_time" value="40"/>
        <Param name="noise_suppressor_flag" value="1"/>
        <Param name="auto_gain_control_flag" value="0"/>
        <Param name="huawei_stream_encryption" value="0"/>
        <Param name="traffic_shaping_flag" value="1"/>
        <Param name="traffic_shaping_max_tasknum" value="100"/>
        <Param name="traffic_shaping_schedule_interval" value="1"/>
        <Param name="traffic_shaping_bitrate_QCIF" value="300"/>
        <Param name="traffic_shaping_bitrate_CIF" value="600"/>
        <Param name="traffic_shaping_bitrate_D1" value="1500"/>
        <Param name="traffic_shaping_bitrate_720p" value="3000"/>
        <Param name="traffic_shaping_bitrate_1080p" value="6000"/>
        <Param name="emergency_videocall_flag" value="0"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_lmproxy" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_meta" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
        <Svc name="mrs_node_mgr_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/dec_vgw_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="dec_vgw_agent" code_type="cplus" user="ubp" team="BDC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_dec_vgw"/>
        <Param name="node_id" value="99900002"/>
        <Param name="dbenable" value="True"/>
        <Param name="bcc_port" value="5063"/>
        <Param name="sdk_log" value="False"/>
        <Param name="jitter_thd" value="100"/>
        <Param name="hikvision_sdk_connect_max_timeout" value="1000"/>
        <Param name="hikvision_ds64xxhd_t_streamtype" value="1"/>
        <Param name="minpfranum" value="0"/>
        <Param name="pfradamagenum" value="1"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" entry="CreateModule"/>
        <Module lib="ubp_error" entry="CreateModule"/>
        <Module lib="ubp_threadpool" entry="CreateModule"/>
        <Module lib="ubp_timer" entry="CreateModule"/>
        <Module lib="ubp_encryption" entry="CreateModule"/>
        <Module lib="ubp_dao" entry="CreateModule"/>
        <Module lib="ubp_mq" entry="CreateModule"/>
        <Module lib="ubp_fmproxy" entry="CreateModule"/>
        <Module lib="ubp_lmproxy" entry="CreateModule"/>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/ftp_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="ftp_agent" code_type="java" user="ubp" team="UDC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="start_java" value="${UDC_HOME}/bin/runFTP.sh"/>
        <Param name="pid_java" value="${UDC_HOME}/bin/checkFTP.sh"/>
        <Param name="stop_java" value="${UDC_HOME}/bin/downFTP.sh"/>
      </SvcParams>
      <LoadModules>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/lm_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="lm_agent" code_type="cplus" user="ubp" team="PLT" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_lm"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" entry="CreateModule"/>
        <Module lib="ubp_error" entry="CreateModule"/>
        <Module lib="ubp_threadpool" entry="CreateModule"/>
        <Module lib="ubp_timer" entry="CreateModule"/>
        <Module lib="ubp_encryption" entry="CreateModule"/>
        <Module lib="ubp_dao" entry="CreateModule"/>
        <Module lib="ubp_mq" entry="CreateModule"/>
        <Module lib="ubp_fmproxy" entry="CreateModule"/>
        <Module lib="ubp_lmproxy" entry="CreateModule"/>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/push_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="push_agent" code_type="java" user="ubp" team="UDC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="start_java" value="/opt/UDC/bin/start_openfire.sh"/>
        <Param name="pid_java" value="/opt/UDC/bin/openfire_pid.sh"/>
        <Param name="stop_java" value="/opt/UDC/bin/stop_openfire.sh"/>
        <Param name="init_wait_time" value="180"/>
      </SvcParams>
      <LoadModules>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/bdc_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="bdc_agent" code_type="cplus" user="ubp" team="BDC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_bdc"/>
        <Param name="dbenable" value="True"/>
        <Param name="dependsvc" value="cm_agent"/>
        <Param name="adaptive_transcoding_switch" value="0"/>
        <Param name="sendrate_calculate_interval" value="5"/>
        <Param name="bitrate_downshift_interval" value="15"/>
        <Param name="bitrate_upshift_interval" value="60"/>
        <Param name="bitrate_downshift_factor" value="5"/>
        <Param name="bitrate_upshift_factor" value="10"/>
        <Param name="sendrate_filter_factor" value="20"/>
        <Param name="lossrate_filter_factor" value="20"/>
        <Param name="jitter_filter_factor" value="20"/>
        <Param name="lossrate_threshold" value="10"/>
        <Param name="jitter_threshold" value="3600"/>
        <Param name="min_bitrate_QCIF" value="64"/>
        <Param name="min_bitrate_CIF" value="128"/>
        <Param name="min_bitrate_D1" value="256"/>
        <Param name="min_bitrate_720p" value="512"/>
        <Param name="min_bitrate_1080p" value="1024"/>
        <Param name="max_bitrate_QCIF" value="256"/>
        <Param name="max_bitrate_CIF" value="1024"/>
        <Param name="max_bitrate_D1" value="2048"/>
        <Param name="max_bitrate_720p" value="4096"/>
        <Param name="max_bitrate_1080p" value="8192"/>
        <Param name="default_bitrate_QCIF" value="128"/>
        <Param name="default_bitrate_CIF" value="256"/>
        <Param name="default_bitrate_D1" value="1024"/>
        <Param name="default_bitrate_720p" value="2048"/>
        <Param name="default_bitrate_1080p" value="4096"/>
        <Param name="x264_tune" value="zerolatency"/>
        <Param name="x264_profile" value="baseline"/>
        <Param name="x264_keyint_max" value="25"/>
        <Param name="x264_keyint_min" value="25"/>
        <Param name="x264_qcomp" value="6"/>
        <Param name="video_jitt" value="80"/>
        <Param name="source_filter" value="0"/>
        <Param name="rtp_loss_thd" value="40"/>
        <Param name="congest_timer" value="200"/>
        <Param name="congest_rel_timer" value="100"/>
        <Param name="congest_pre_thd" value="300"/>
        <Param name="congest_rel_hys" value="50"/>
        <Param name="jitter_filter" value=".001"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/maintain_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="maintain_agent" code_type="cplus" user="ubp" team="PLT" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_maintain"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/mrs_mgr_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="mrs_mgr_agent" code_type="cplus" user="ubp" team="MRS" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_mrs_mgr"/>
        <Param name="dbenable" value="True"/>
        <Param name="db_max_conn" value="5"/>
        <Param name="db_min_conn" value="3"/>
        <Param name="check_orphan_file_hour" value="3"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_svcmgr" entry="CreateModule"/>
        <Module lib="ubp_threadpool" entry="CreateModule"/>
        <Module lib="ubp_timer" entry="CreateModule"/>
        <Module lib="ubp_encryption" entry="CreateModule"/>
        <Module lib="ubp_dao" entry="CreateModule"/>
        <Module lib="ubp_mq" entry="CreateModule"/>
        <Module lib="ubp_fmproxy" entry="CreateModule"/>
        <Module lib="ubp_lmproxy" entry="CreateModule"/>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>
