=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/svc_agent_4.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
file      : \code\src\platform\modules\sca\svc_agenty.xsd
install   : \install\conf\svc_agenty.xsd
author    : ZhongWei
created   : 2012/10/30 13:30
changed	  : 2015-4-17 2:38 to support 4.0 by huangchunlun 
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/sca/xml">
	<xsd:complexType name="Param_t">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="SvcParams_t">
		<xsd:sequence>
			<xsd:element name="Param" type="sca:Param_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  
	<xsd:complexType name="Module_t">
		<xsd:attribute name="lib" type="xsd:string" use="required"/>
		<xsd:attribute name="entry" type="xsd:string" default="CreateModule"/>
	</xsd:complexType>
	<xsd:complexType name="LoadModules_t">
		<xsd:sequence>
			<xsd:element name="Module" type="sca:Module_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="LoadPB_t">
		<xsd:sequence>
			<xsd:element name="PB" type="sca:Module_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Svc_t">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="DependSvcs_t">
		<xsd:sequence>
			<xsd:element name="Svc" type="sca:Svc_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  
  <xsd:complexType name="ServiceInfo_t">
    <xsd:sequence>
      <xsd:element name="SvcParams" type="sca:SvcParams_t" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="LoadModules" type="sca:LoadModules_t" maxOccurs="unbounded" minOccurs="0"/>
	  <xsd:element name="LoadPB" type="sca:LoadPB_t" maxOccurs="unbounded" minOccurs="0"/>
	  <xsd:element name="DependSvcs" type="sca:DependSvcs_t" maxOccurs="unbounded" minOccurs="0"/>	  
    </xsd:sequence>
    <xsd:attribute name="svc_type" type="xsd:string" use="required"/>
	<xsd:attribute name="code_type" type="xsd:string" use="required"/>
	<xsd:attribute name="valgrind_trigger" type="xsd:string" use="optional" default="off" />
	<xsd:attribute name="tcmalloc_trigger" type="xsd:string" use="optional" default="off" />
	<xsd:attribute name="user" type="xsd:string" use="required"/>
	<xsd:attribute name="team" type="xsd:string" use="required"/>
  </xsd:complexType>
  
	<xsd:complexType name="SvcAgent_t">
		<xsd:sequence>
			<xsd:element name="ServiceInfo" type="sca:ServiceInfo_t" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	
  <xsd:element name="svcagent" type="sca:SvcAgent_t"/>
  
</xsd:schema>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/km_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="km_agent" code_type="cplus" user="ubp" team="BCC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="ubp_km"/>
        <Param name="dbenable" value="true"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" />
        <Module lib="ubp_error" />
        <Module lib="ubp_threadpool" />
        <Module lib="ubp_timer" />
        <Module lib="ubp_encryption" />
        <Module lib="ubp_dao" />
        <Module lib="ubp_mq" />
        <Module lib="ubp_fmproxy" />
        <Module lib="ubp_lmproxy" />
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/eir_agent.xml
<?xml version="1.0" encoding="utf-8"?>
<sca:svcagent xmlns:sca="http://www.td-tech.com/ubp/platform/sca/xml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.td-tech.com/ubp/platform/sca/xml svc_agent_4.0.xsd"
         name="svc_agent">
         <!-- tcmalloc_trigger="on" ： open tcmalloc -->
         <!-- valgrind_trigger="on" ： open valgrind -->
    <ServiceInfo svc_type="eir_agent" code_type="cplus" user="ubp" team="UDC" tcmalloc_trigger="off" valgrind_trigger="off">
      <SvcParams>
        <Param name="dllvalue" value="udc_eir"/>
      </SvcParams>
      <LoadModules>
        <Module lib="ubp_sca" entry="CreateCfgMgr" />
        <Module lib="ubp_svcmgr" entry="CreateModule"/>
        <Module lib="ubp_error" entry="CreateModule"/>
        <Module lib="ubp_threadpool" entry="CreateModule"/>
        <Module lib="ubp_timer" entry="CreateModule"/>
        <Module lib="ubp_encryption" entry="CreateModule"/>
        <Module lib="ubp_dao" entry="CreateModule"/>
        <Module lib="ubp_mq" entry="CreateModule"/>
        <Module lib="ubp_fmproxy" entry="CreateModule"/>
        <Module lib="ubp_lmproxy" entry="CreateModule"/>
        <Module lib="ubp_lic_man_proxy" entry="CreateModule"/>
      </LoadModules>
      <LoadPB>
      </LoadPB>
      <DependSvcs>
        <Svc name="cm_agent" />
        <Svc name="lic_man_agent" />
      </DependSvcs>
    </ServiceInfo>
</sca:svcagent>
