=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/svctype_info.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:svcmgr="http://www.td-tech.com/ubp/platform/svcmgr/xml"
            targetNamespace="http://www.td-tech.com/ubp/platform/svcmgr/xml">
	
	<xsd:complexType name="ServiceType_t">
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="defaultname" type="xsd:string" use="required"/>
		<xsd:attribute name="svc_mode" type="xsd:string" use="required"/>
		<xsd:attribute name="pubport" type="xsd:int" use="required"/>
		<xsd:attribute name="dealport" type="xsd:int" use="required"/>
		<xsd:attribute name="ip_type" type="xsd:int" use="required"/>
		<xsd:attribute name="cpu_group" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="ServiceTypeInfo_t">
		<xsd:sequence>
			<xsd:element name="ServiceType" type="svcmgr:ServiceType_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="port_offset" type="xsd:int" use="required"/>
		<xsd:attribute name="broker_dealport" type="xsd:int" use="required"/>
		<xsd:attribute name="broker_pubport" type="xsd:int" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="ServiceProxy_t">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="proxy_ip" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="ProxyPolicy_t">
		<xsd:sequence>
			<xsd:element name="ServiceProxy" type="svcmgr:ServiceProxy_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="default_ip" type="xsd:string" use="required"/>
		<xsd:attribute name="active_subpolicy" type="xsd:boolean" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="SvcTypePolicy_t">
		<xsd:sequence>
			<xsd:element name="ProxyPolicy" type="svcmgr:ProxyPolicy_t" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ServiceTypeInfo" type="svcmgr:ServiceTypeInfo_t" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
  <xsd:element name="svctypepolicy" type="svcmgr:SvcTypePolicy_t"/>
  
</xsd:schema>

=== Noel1992/eSDK_eLTE_SDK_Windows/src/platform/SDK/conf/svctype_info.xml
<?xml version="1.0" encoding="utf-8"?>
<svcmgr:svctypepolicy xmlns:svcmgr="http://www.td-tech.com/ubp/platform/svcmgr/xml"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://www.td-tech.com/ubp/platform/svcmgr/xml svctype_info.xsd">
<ProxyPolicy default_ip="signal_ip" active_subpolicy="true">
     <ServiceProxy name="ubp_ue" proxy_ip="NON_MDC"/>
      <ServiceProxy name="ubp_afee" proxy_ip="NON_MDC"/>
     <ServiceProxy name="ubp_bcc" proxy_ip="MDC_21"/>

</ProxyPolicy>

<ServiceTypeInfo port_offset="0" broker_dealport="22999" broker_pubport="22998">
<ServiceType type="adm_agent" defaultname="ubp_adm" svc_mode="ipc" pubport="0" dealport="0" ip_type="0" cpu_group="om_t" />

<ServiceType type="daem_agent" defaultname="ubp_daem" svc_mode="ipc" pubport="20001" dealport="20002" ip_type="0" cpu_group="om_t" />

<ServiceType type="mq_broker_agent" defaultname="ubp_mq_broker" svc_mode="ipc" pubport="20015" dealport="20016" ip_type="0" cpu_group="om_t" />

<ServiceType type="security_agent" defaultname="ubp_security" svc_mode="ipc" pubport="20019" dealport="20020" ip_type="2" cpu_group="om_t" />

<ServiceType type="cm_agent" defaultname="ubp_cm" svc_mode="ipc" pubport="20100" dealport="20005" ip_type="0" cpu_group="om_t" />

<ServiceType type="fm_agent" defaultname="ubp_fm" svc_mode="ipc" pubport="20007" dealport="20008" ip_type="0" cpu_group="om_t" />

<ServiceType type="lm_agent" defaultname="ubp_lm" svc_mode="ipc" pubport="20010" dealport="20011" ip_type="0" cpu_group="om_t" />

<ServiceType type="mon_agent" defaultname="ubp_monitor" svc_mode="ipc" pubport="20013" dealport="20014" ip_type="0" cpu_group="om_t" />

<ServiceType type="maintain_agent" defaultname="ubp_maintain" svc_mode="ipc" pubport="20017" dealport="20018" ip_type="0" cpu_group="om_t" />

<ServiceType type="ue_agent" defaultname="ubp_ue" svc_mode="tcp" pubport="0" dealport="9900" ip_type="0" cpu_group="NA" />

<ServiceType type="lic_man_agent" defaultname="ubp_lic_man" svc_mode="ipc" pubport="22057" dealport="22058" ip_type="0" cpu_group="om_t" />

<ServiceType type="bcc_agent" defaultname="ubp_bcc" svc_mode="ipc" pubport="22001" dealport="22002" ip_type="2" cpu_group="sig_t" />

<ServiceType type="diam_agent" defaultname="ubp_diam" svc_mode="ipc" pubport="22024" dealport="22025" ip_type="2" cpu_group="sig_t" />

<ServiceType type="pres_agent" defaultname="ubp_pres" svc_mode="ipc" pubport="22021" dealport="22026" ip_type="2" cpu_group="sig_t" />

<ServiceType type="hpgw_agent" defaultname="ubp_hpgw" svc_mode="ipc" pubport="22098" dealport="22099" ip_type="2" cpu_group="sig_t" />

<ServiceType type="afee_agent" defaultname="ubp_afee" svc_mode="tcp" pubport="0" dealport="15003" ip_type="0" cpu_group="sig_t" />

<ServiceType type="sds_adapter_agent" defaultname="ubp_sds_adapter" svc_mode="ipc" pubport="22063" dealport="22064" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sds_dataman_agent" defaultname="ubp_sds_dataman" svc_mode="ipc" pubport="22200" dealport="22201" ip_type="2" cpu_group="sig_t" />

<ServiceType type="km_agent" defaultname="ubp_km" svc_mode="ipc" pubport="22027" dealport="22030" ip_type="2" cpu_group="sig_t" />

<ServiceType type="bdc_agent" defaultname="ubp_bdc01" svc_mode="ipc" pubport="22004" dealport="22005" ip_type="2" cpu_group="med_t" />

<ServiceType type="dec_vgw_agent" defaultname="ubp_dec_vgw" svc_mode="ipc" pubport="22022" dealport="22023" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_vgw_agent" defaultname="ubp_mrs_vgw" svc_mode="ipc" pubport="22060" dealport="22061" ip_type="2" cpu_group="med_t" />

<ServiceType type="mrs_ivs_agent" defaultname="ubp_mrs_ivs" svc_mode="ipc" pubport="22074" dealport="22075" ip_type="2" cpu_group="med_t" />

<ServiceType type="mrs_node_mgr_agent" defaultname="ubp_mrs_node_mgr" svc_mode="ipc" pubport="22066" dealport="22067" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_mgr_agent" defaultname="ubp_mrs_mgr" svc_mode="ipc" pubport="22049" dealport="22050" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_rec_man_agent" defaultname="ubp_mrs_rec_man" svc_mode="ipc" pubport="22069" dealport="22070" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_plb_agent" defaultname="ubp_mrs_plb" svc_mode="ipc" pubport="22051" dealport="22052" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_web_agent" defaultname="ubp_mrs_web" svc_mode="ipc" pubport="22053" dealport="22054" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_rec_sinker_agent" defaultname="ubp_mrs_rec_sinker" svc_mode="ipc" pubport="22072" dealport="22073" ip_type="2" cpu_group="med_t" />

<ServiceType type="mrs_vgw_agent" defaultname="ubp_mrs_vgw" svc_mode="ipc" pubport="22076" dealport="22077" ip_type="2" cpu_group="med_t" />

<ServiceType type="mrs_ivs_agent" defaultname="ubp_mrs_ivs" svc_mode="ipc" pubport="22074" dealport="22075" ip_type="2" cpu_group="med_t" />

<ServiceType type="mrs_mgr_agent" defaultname="ubp_mrs_mgr" svc_mode="ipc" pubport="22049" dealport="22050" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_web_agent" defaultname="ubp_mrs_web" svc_mode="ipc" pubport="22053" dealport="22054" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_plb_agent" defaultname="ubp_mrs_plb" svc_mode="ipc" pubport="22051" dealport="22052" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mrs_rec_sinker_agent" defaultname="ubp_mrs_rec_sinker" svc_mode="ipc" pubport="22072" dealport="22073" ip_type="2" cpu_group="med_t" />

<ServiceType type="itf_mgr_agent" defaultname="ubp_itf_manager" svc_mode="ipc" pubport="22096" dealport="22097" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_01" svc_mode="ipc" pubport="22100" dealport="22101" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_02" svc_mode="ipc" pubport="22102" dealport="22103" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_03" svc_mode="ipc" pubport="22104" dealport="22105" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_04" svc_mode="ipc" pubport="22106" dealport="22107" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_05" svc_mode="ipc" pubport="22108" dealport="22109" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_06" svc_mode="ipc" pubport="22110" dealport="22111" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_07" svc_mode="ipc" pubport="22112" dealport="22113" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_08" svc_mode="ipc" pubport="22114" dealport="22115" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_09" svc_mode="ipc" pubport="22116" dealport="22117" ip_type="2" cpu_group="sig_t" />

<ServiceType type="sdk_frm_agent" defaultname="ubp_sdk_agent_10" svc_mode="ipc" pubport="22118" dealport="22119" ip_type="2" cpu_group="sig_t" />

<ServiceType type="gis_agent" defaultname="ubp_gis" svc_mode="ipc" pubport="22028" dealport="22029" ip_type="2" cpu_group="sig_t" />

<ServiceType type="mdm_agent" defaultname="udc_mdm" svc_mode="ipc" pubport="23001" dealport="23002" ip_type="2" cpu_group="udc_t" />

<ServiceType type="uis_agent" defaultname="udc_uis" svc_mode="ipc" pubport="23003" dealport="23004" ip_type="2" cpu_group="udc_t" />

<ServiceType type="eir_agent" defaultname="udc_eir" svc_mode="ipc" pubport="23005" dealport="23006" ip_type="2" cpu_group="udc_t" />

<ServiceType type="aas_agent" defaultname="udc_aas" svc_mode="ipc" pubport="23007" dealport="23008" ip_type="2" cpu_group="udc_t" />

<ServiceType type="tis_agent" defaultname="udc_tis" svc_mode="ipc" pubport="23009" dealport="23010" ip_type="2" cpu_group="udc_t" />

<ServiceType type="uom_agent" defaultname="udc_uom" svc_mode="ipc" pubport="23011" dealport="23012" ip_type="2" cpu_group="udc_t" />

<ServiceType type="web_agent" defaultname="udc_web" svc_mode="ipc" pubport="23013" dealport="23014" ip_type="2" cpu_group="udc_t" />

<ServiceType type="push_agent" defaultname="udc_push" svc_mode="ipc" pubport="23015" dealport="23016" ip_type="2" cpu_group="udc_t" />

<ServiceType type="omp_agent" defaultname="udc_omp" svc_mode="ipc" pubport="23017" dealport="23018" ip_type="2" cpu_group="udc_t" />

<ServiceType type="med_agent" defaultname="udc_med" svc_mode="ipc" pubport="23019" dealport="23020" ip_type="2" cpu_group="udc_t" />

<ServiceType type="opm_agent" defaultname="udc_opm" svc_mode="ipc" pubport="23021" dealport="23022" ip_type="2" cpu_group="udc_t" />

<ServiceType type="ftp_agent" defaultname="udc_ftp" svc_mode="ipc" pubport="23023" dealport="23024" ip_type="2" cpu_group="udc_t" />

</ServiceTypeInfo>
</svcmgr:svctypepolicy>
